### ISSUE TITLE
Set WORKDIR value in container definition

### ISSUE THREAD

**Issue by brianredbeard** [n3wscott/sockeye#9]
Due to an outstanding bug in `containerd` (https://github.com/containerd/containerd/pull/4669) there is a problem when the value `WORKDIR` is set and user namespaces are in effect.

More detail on this can be seen in: https://github.com/kubernetes-sigs/kind/issues/1331

In the meantime, as a workaround in the event that `WORKDIR` cannot be set, the value `workingDir: /` can be added to the container spec in the KNative serving definition, e.g.:

```yaml
spec:
  template:
    metadata:
      creationTimestamp: null
    spec:
      containerConcurrency: 0
      containers:
        - image: >-
            docker.io/n3wscott/sockeye:v0.7.0@sha256:e603d8494eeacce966e57f8f508e4c4f6bebc71d095e3f5a0a1abaf42c5f0e48
          name: user-container
          readinessProbe:
            successThreshold: 1
            tcpSocket:
              port: 0
          resources: {}
          workingDir: /
```

This sets `WORKDIR`/`workingDir` to a value which will not necessitate any additional operations within the container.
